######################################################################
# Automatically generated by qmake (3.0) ?? ??? 3 09:17:39 2015
######################################################################

QT += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = empty_program
TEMPLATE = app

# Directories
SOURCES += main.cpp \
            myhead.cpp
HEADERS += myhead.h
